<?php

namespace Alsharie\AdenBankPayment\Responses;


class AdenBankInitPaymentResponse extends AdenBankResponse
{


    /**
     * Status Message
     * @return false|mixed
     */
    public function getMsg()
    {
        if (!empty($this->data['msg'])) {
            return $this->data['msg'];
        }

        return false;
    }

    /**
     * unique number generated by bank to allow you for the next step .
     * approval ID only can be used by merchant within 10 minutes
     * otherwise the merchant shall generate another one be sending a new
     * request
     * @return false|mixed
     *
     */
    public function getApprovalID()
    {
        if (!empty($this->data['ApprovalID'])) {
            return $this->data['ApprovalID'];
        }

        return false;
    }


}
